### PR TITLE
contact form

### PR DESCRIPTION
**Pull request by udipta**

### CODE REVIEW

**Comment by shubham399** [comment]
What why?

**Comment by shubham399** [comment]
Let that branch be there

**Comment by udipta** [comment]
we changing the entire contact page

**Comment by shubham399** [comment]
Why need to backend?

**Comment by udipta** [comment]
some issue is there in pull request to master to i pull request to backend (sorry)

**Comment by shubham399** [comment]
close the PR then

**Comment by rahuljain5** [comment]
Alternative approach taken

**Pull request closed without merging**
